api/urls.py
# api/urls.py
from django.urls import path
from .views import ExpenseAPIView
from .views import RevenueAPIView

urlpatterns = [
    path('expense', ExpenseAPIView.as_view()),
    path('revenue', RevenueAPIView.as_view()),
    #path('expense/<int:pk>/edit', ExpenseUpdateDemoView.as_view(), name='expense_edit_demo'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    # Django admin
    path('admin/', admin.site.urls),

    # User management
    path('accounts/', include('django.contrib.auth.urls')), #new

    # Local apps
    path('', include('transactions.urls')),
    path('api/', include('api.urls')), 

   
]

transactions/urls.py
# transactions/urls.py
from django.urls import path
from django.views.generic import TemplateView
from .views import (
    HomePageView, 
    AboutPageView, 
    DemoPageView,
    TransactionUpdateView, 
    TransactionDeleteView,
    TransactionListView,
    UnmatchedTransactionListView,
    StatementCreateView,
    StatementListView, 
    StatementDeleteView,
    #transaction_list, 
    CreateExpenseView,
    ExpenseListView,
    ExpenseUpdateView,
    ExpenseDeleteView,
    CreateRevenueView,
    UploadDocumentView,
    CreateMatchingRevenueView,
    CreateMatchingExpenseView,
    MatchingRevenueListView,
    RevenueListView,
    RevenueUpdateView,
    RevenueDeleteView,
    DocumentListView,
    DocumentDeleteView,
    MatchingExpenseListView,
    MatchingRevenueListView,
    UploadMultipleInvoicesView,
    GetTaxReportView,
    RawInvoiceListView,
    RawInvoiceEditView,
    RawInvoiceDeleteView,
    ReviewInvoiceListView,
    ReviewInvoiceEditView,
    match_expense,
    match_revenue,
    remove_match,
    FileInvoiceView,
    get_suites,
    get_expense_list,
    get_revenue_list,
    get_expense_edit,
    get_revenue_edit,
    get_expense_row,
    get_revenue_row,
    add_revenue_submit,
    add_expense_submit,
    add_matching_expense_submit,
    edit_matching_expense,
    get_matching_expense_row,
    add_revenue,
    add_expense,
    cancel_new_record,
    delete_expense,
    delete_revenue,
    add_matching_expense,
    get_transaction_list,
    get_transaction_edit,
    get_transaction_row,
    delete_transaction,
    get_unmatched_transaction_list,
    get_test_form,
    
)

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('about/', AboutPageView.as_view(), name='about'),
    path('demo/', DemoPageView.as_view(), name='demo'),
    path('upload_statement/', StatementCreateView.as_view(), name='upload_statement'),
    path('upload_invoice/', CreateExpenseView.as_view(), name='upload_invoice'),
    path('upload_check/', CreateRevenueView.as_view(), name='upload_check'),
    path('upload_document', UploadDocumentView.as_view(), name='upload_document'),
    path('<int:pk>/create_matching_revenue/', CreateMatchingRevenueView.as_view(), name='create_matching_revenue'),
    #path('<int:pk>/create_matching_expense/', CreateMatchingExpenseView.as_view(), name='create_matching_expense'),
    path('list_transactions/', TransactionListView.as_view(), name='transaction_list'),
    path('list_unmatched_transactions/', UnmatchedTransactionListView.as_view(), name='unmatched_transaction_list'),
    path('<int:pk>/transaction_edit/', TransactionUpdateView.as_view(), name='transaction_edit'),
    #path('<int:pk>/expense_edit/', ExpenseUpdateView.as_view(), name='expense_edit'),
    path('<int:pk>/expense_delete/', ExpenseDeleteView.as_view(), name='expense_delete'),
    path('list_expenses/', ExpenseListView.as_view(), name='expense_list'),
    path('list_revenues/', RevenueListView.as_view(), name='revenue_list'),
    path('list_document/', DocumentListView.as_view(), name='document_list'),
    path('<int:pk>/document_delete/', DocumentDeleteView.as_view(), name='document_delete'),
    #path('<int:pk>/revenue_edit', RevenueUpdateView.as_view(),name='revenue_edit'),
    path('<int:pk>/revenue_delete/', RevenueDeleteView.as_view(), name='revenue_delete'),
    path('<int:pk>/list_matching_revenues/', MatchingRevenueListView.as_view(), name='matching_revenue_list'),
    path('<int:pk>/list_matching_expenses/', MatchingExpenseListView.as_view(), name='matching_expense_list'),
    path('upload_multiple_invoices/', UploadMultipleInvoicesView.as_view(), name='upload_multiple_invoices'),
    path('get_tax_report/', GetTaxReportView.as_view(), name='get_tax_report'),
    path('list_statements/', StatementListView.as_view(), name='statement_list'),
    path('<int:pk>/delete_statement/', StatementDeleteView.as_view(), name='statement_delete'),

    #path('<int:pk>/list_matches/', MatchListView.as_view(), name='match_list'),
    path('<int:transaction_pk>/<int:expense_pk>/match_expense', match_expense, name='match_expense'),
    path('<int:transaction_pk>/remove_match', remove_match, name='remove_match'),
    path('<int:transaction_pk>/<int:revenue_pk>/match_revenue', match_revenue, name='match_revenue'),
    path('<int:pk>/transaction_delete', TransactionDeleteView.as_view(), name='transaction_delete'),
    path('raw_invoices/', RawInvoiceListView.as_view(), name='raw_invoices'),
    path('review_invoices/', ReviewInvoiceListView.as_view(), name='review_invoices'),
    path('<int:pk>/raw_invoice_edit/', RawInvoiceEditView.as_view(), name='raw_invoice_edit'),
    path('<int:pk>/review_invoice_edit/', ReviewInvoiceEditView.as_view(), name='review_invoice_edit'),
    path('<int:pk>/raw_invoice_delete/', RawInvoiceDeleteView.as_view(), name='raw_invoice_delete'),
    path('<int:pk>/file_invoice/', FileInvoiceView.as_view(), name='file_invoice'),

    path('get_suites', get_suites, name='get_suites'),
    path('get_expense_list', get_expense_list, name='get_expense_list'),
    path('get_revenue_list', get_revenue_list, name='get_expense_list'),
    path('<int:expense_pk>/expense_edit', get_expense_edit, name='get_expense_edit'),
    path('<int:expense_pk>/expense_row', get_expense_row, name='get_expense_row'),
    path('<int:revenue_pk>/revenue_edit', get_revenue_edit, name='get_revenue_edit'),
    path('<int:revenue_pk>/revenue_row', get_revenue_row, name='get_revenue_row'),
    path('<int:transaction_pk>/<int:expense_pk>/edit_matching_expense', edit_matching_expense, name='edit_matching_expense'),
    path('<int:expense_pk>/get_matching_expense_row', get_matching_expense_row, name='get_matching_expense_row'),
    path('add_matching_expense_submit', add_matching_expense_submit, name='add_matching_expense_submit'),
    path('add_revenue', add_revenue, name='add_revenue'),
    path('add_expense', add_expense, name='add_expense'),
    path('add_revenue_submit', add_revenue_submit, name='add_revenue_submit'),
    path('add_expense_submit', add_expense_submit, name='add_expense_submit'),
    path('cancel_new_record', cancel_new_record, name='cancel_new_record'),
    path('<int:expense_pk>/delete_expense', delete_expense, name='delete_expense'),
    path('<int:revenue_pk>/delete_revenue', delete_revenue, name='delete_revenue'),
    path('add_matching_expense/', add_matching_expense, name='add_matching_expense'),
    path('<int:transaction_pk>/trasaction_edit', get_transaction_edit, name='get_transaction_edit'),
    path('get_transaction_list', get_transaction_list, name='get_transaction_list'),
    path('get_unmatched_transaction_list', get_unmatched_transaction_list, name='get_unmatched_transaction_list'),
    path('<int:transaction_pk>/transaction_row', get_transaction_row, name='get_transaction_row'),
    path('<int:transaction_pk>/delete_transaction', delete_transaction, name='delete_transaction'),
    path('test_form', get_test_form, name='test_form'),

]

transactions/models.py
from django.db import models
from django.contrib.auth import get_user_model
from common.utils import format_for_storage
from datetime import datetime
from django.conf import settings
from common.utils import store_in_gcs, GCS_ROOT_BUCKET, get_full_path_to_gcs
import os

#logging.basicConfig(filename='example.log', level=logging.DEBUG)

# Create your models here.
class Statement(models.Model):
    record_dir = 'statements'

    choices = [
        ('credit_card', 'Credit Card'),
        ('bank', 'Bank')
    ]

    period_ending_date = models.DateField()
    account_number = models.CharField(max_length=4)
    statement_type = models.CharField(max_length=20, choices=choices)
    uploaded_file = models.FileField()
    #is_verified = models.BooleanField()
    author = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE
    ) 
    date_uploaded = models.DateField(auto_now=True)

    def get_full_path_to_gcs(self):
        year = self.period_ending_date.year
        return 'https://storage.cloud.google.com/{}/{}/{}'.format(GCS_ROOT_BUCKET, self.get_statement_folder(), self.uploaded_file.name)
    
    def get_statement_folder(self):
        year = self.period_ending_date.year
        return '{}/{}'.format(self.record_dir, year)
    def save(self, *args, **kwargs):
        ## Looks a bit hacky but this needs to happen in this exact sequence. 
        # If we try to delete the file before saving, then we would get the 'file is being processed error'.
        if self.uploaded_file.name:
            store_in_gcs([self.uploaded_file], GCS_ROOT_BUCKET, self.get_statement_folder())
        super().save(*args, **kwargs)

class Transaction(models.Model):
    transaction_date = models.DateField()
    statement = models.ForeignKey(
        Statement,
        on_delete=models.CASCADE,
        related_name='transactions'
    )
    transaction_description = models.TextField(max_length=500)
    transaction_amount = models.DecimalField(max_digits=20, decimal_places=2)
    match_id = models.BigIntegerField(default=0)
    is_ignored = models.BooleanField(default=False)
    
    def __str__(self):
        return self.transaction_description
    
    def get_matching_record(self):
        if self.transaction_amount >= 0:
            return Revenue.objects.get(pk=self.match_id)
        else:
            return Expense.objects.get(pk=self.match_id)

    matching_record = property(get_matching_record)

class Property(models.Model):
    address = models.CharField(max_length=50)
    purchase_price = models.DecimalField(max_digits=20, decimal_places=2, default=0)
    market_price = models.DecimalField(max_digits=20, decimal_places=2, default=0)
    full_address = models.CharField(max_length=200, blank=True, null=True)

    def __str__(self):
        return self.address

class Rental_Unit(models.Model):
    address = models.ForeignKey(
        Property,
        on_delete=models.CASCADE,
        related_name='rental_units'
    )
    suite = models.CharField(max_length=50, blank=True)
    is_current = models.BooleanField(default=True)

    def __str__(self):
        return '{} {}'.format(self.address, self.suite)

class Raw_Invoice(models.Model):
    directory = 'unfiled_invoices'
    upload_date = models.DateTimeField(auto_now=True)
    invoice_image = models.TextField(max_length=500)
    file_hash = models.TextField(max_length=32, unique=True)
    tax_year = models.IntegerField()
    date_filed = models.DateTimeField(blank=True, null=True)
    need_review = models.BooleanField(default=False)
    note = models.TextField(max_length = 500, default="", blank=True, null=True)
    author = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE,
        blank = True,
        null = True,
    )
    
    def get_full_path_to_gcs(self):
        return get_full_path_to_gcs(self.get_relative_path_to_gcs())

    def get_relative_path_to_gcs(self):
        return '{}/{}'.format(self.directory, self.invoice_image)
    
    def __str__(self):
        return self.invoice_image


class Record(models.Model):
    GCS_ROOT_BUCKET = 'tran_ba_investment_group_llc'

    record_dir = 'temp'

    record_date = models.DateField()
    address = models.ForeignKey(
        Rental_Unit,
        on_delete=models.CASCADE,
        related_name='records'
    )
    amount = models.DecimalField(max_digits=20, default = 0, decimal_places=2)
    document_image = models.FileField(blank=True, null=True)
    document_hash = models.TextField(max_length=32, unique=True, blank=True, null=True)
    note = models.TextField(max_length = 500, blank=True, null=True)

    date_filed = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE,
    )

    def get_full_path_to_gcs(self):
        return get_full_path_to_gcs(self.get_relative_path_to_gcs())

    def get_relative_path_to_gcs(self):
        year = self.record_date.year
        return '{}/{}'.format(self.get_record_folder(), self.document_image.name)
    
    def get_record_folder(self):
        formatted_address = format_for_storage(str(self.address.address))
        year = self.record_date.year
        return '{}/{}/{}'.format(formatted_address, self.record_dir, year)

class Expense_Category(models.Model):
    expense_category = models.CharField(max_length=50)
    def __str__(self):
        return self.expense_category

class Expense(Record):
    record_dir = 'invoices'
    """ EXPENSE_TYPES = (
        ("misc", "Misc"),
        ('advertising', 'Advertising'),
        ('management_fee', 'Management Fee'),
        ('trash', 'Trash'),
        ('water', 'Water'),
        ('power', 'Power'),
        ('gas', 'Gas'),
        ('insurance', 'Insurance'),
        ('repair_maintenance', 'Repair and Maintenance'),
        ('roof', 'Roof'),
        ('landscaping', 'Landscaping'),
        ('commission', 'Commission'),
        ('taxes_and_fees', 'Taxes & Fees'),
        ('payroll', 'Payroll'),
        ('payroll tax', 'Payroll Tax'),
        ('property_purchase', 'Property Purchase')
    ) """
    raw_invoice = models.ForeignKey(
        Raw_Invoice,
        models.SET_NULL,
        blank=True,
        null=True,
    )
    expense_category = models.ForeignKey(
        Expense_Category,
        on_delete = models.CASCADE,
        blank = True,
        null = True,
    )

class Revenue(Record):
    record_dir = 'checks'
    REVENUE_TYPES = (
        ('reimb','Reimbursement'),
        ('rent', 'Rent'),
        ('discounts_and_cashbacks', 'Discounts and Cashbacks')
    )
    revenue_type = models.CharField(max_length=50, choices = REVENUE_TYPES, default='rent')

class Document(Record):
    record_dir = 'documents'

transactions/forms.py
from os import path
from django import forms
from .models import Transaction, Expense, Revenue, Statement, Raw_Invoice, Rental_Unit, Document
from django.forms.widgets import ClearableFileInput
from datetime import datetime

class StatementUploadForm(forms.ModelForm):
    class Meta:
        model = Statement
        exclude = ['author', 'date_uploaded']
        labels = {
            'uploaded_file': 'Upload a file'
        }

class TransactionUpdateForm(forms.ModelForm):
   class Meta:
       model = Transaction
       exclude = ['statement', 'transaction_date', 'match_id','transaction_amount']

class RawInvoiceUpdateForm(forms.ModelForm):
    class Meta:
        model = Raw_Invoice
        exclude = ['upload_date', 'file_hash', 'invoice_image','date_filed','author']

class CreateExpenseForm(forms.ModelForm):
    address = forms.ModelChoiceField(queryset=Rental_Unit.objects.filter(is_current=True).order_by('address__address','suite'))
    class Meta:
        model = Expense
        exclude = ['author', 'date_uploaded','date_filed','raw_invoice','next','document_hash']
        #widgets = {'next' :  forms.HiddenInput()}

class UpdateRevenueForm(forms.ModelForm):
    class Meta:
        model = Revenue
        exclude = ['author', 'date_uploaded', 'document_hash']

class UpdateExpenseForm(forms.ModelForm):
    class Meta:
        model = Expense
        exclude = ['author', 'date_uploaded', 'date_filed','raw_invoice', 'document_hash']

class CreateRevenueForm(forms.ModelForm):
    address = forms.ModelChoiceField(queryset=Rental_Unit.objects.filter(is_current=True).order_by('address__address','suite'))
    class Meta:
        model = Revenue
        exclude = ['date_uploaded', 'author', 'document_hash']
        #widgets = {'author' :  forms.HiddenInput()}

# class UpdateTransactionForm(forms.ModelForm):
#     class Meta:
#         model = Transaction
#         fields = ['transaction_description']

class UploadDocumentForm(forms.ModelForm):
    address = forms.ModelChoiceField(queryset=Rental_Unit.objects.order_by('address__address','suite'))
    class Meta:
        model = Document
        exclude = ['author', 'date_uploaded', 'amount', 'document_hash']

class SelectTaxYearForm(forms.Form):
    current_year = datetime.now().year
    start_year = 2021
    end_year = current_year
    years = [(str(i), str(i)) for i in range(start_year, current_year+1)]
    tax_year = forms.ChoiceField(
        required=False,
        widget=forms.Select,
        choices=years,
        initial=str(current_year),
    )

class MultipleFileInput(forms.ClearableFileInput):
    allow_multiple_selected = True

class MultipleFileField(forms.FileField):
    def __init__(self, *args, **kwargs):
        kwargs.setdefault("widget", MultipleFileInput())
        super().__init__(*args, **kwargs)

    def clean(self, data, initial=None):
        single_file_clean = super().clean
        if isinstance(data, (list, tuple)):
            result = [single_file_clean(d, initial) for d in data]
        else:
            result = single_file_clean(data, initial)
        return result

class UploadMultipleInvoicesForm(forms.Form):
    current_year = datetime.now().year
    years = [(str(i), str(i)) for i in range(current_year-2, current_year+2)]
    tax_year = forms.ChoiceField(
        required=False,
        widget=forms.Select,
        choices=years,
        initial=str(current_year),
    )
    invoices = MultipleFileField()

templates/transactions/document_list.html
{% extends '_record_list.html' %}
{% load humanize %}

{% block top_nav %}
  <a class="p-2 text-dark" href="{% url 'upload_document' %}">New Document</a>
{% endblock top_nav %}
{% block table_content %}
<table class="table table-striped" style="width:auto">
    <thead>
      <tr>
        <th scope="col">Document Date</th>
        <th scope="col">Address</th>
        <th scope="col">Document Image</th>
        <th scope="col">Note </th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      {% for document in page_obj.object_list %}
      <tr>
        <td>{{ document.record_date }}</td>
        <td>{{ document.address }}</td>
        <td><a href="{{ document.get_full_path_to_gcs }}">{{ document.document_image.name }}</a></td>
        <td>{{ document.note }}</td>
        <td><a href="{% url 'document_delete' document.pk %}">Delete</a></td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock table_content %}

templates/transactions/document_upload.html
{% extends '_base.html' %}

{% block content %}
    <form action="" method="POST" enctype="multipart/form-data">{% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-info ml-2 preventDouble" type="submit">Upload</button>
    </form>
{% endblock content %}

templates/transactions/expense_list.html
{% extends '_record_list_ajax.html' %}

{% block extra_form %}
<!-- &nbsp;&nbsp;
<input type="checkbox" id="unmatched_expense" name="unmatched_expense" value="yes">
<label for="unmatched_invoice">Unmatched invoice</label> -->
<label for="category"> Category: </label>
<select name="category" id="category">
  <option value="all">All</option>
  {% for category in categories %}
      <option value="{{ category }}">{{ category }}</option>
  {% endfor %}
</select>
&nbsp;&nbsp;
<label for="order_by"> Sort by: </label>
<select name="order_by" id="order_by" value="">
  <option value="-date_filed">New</option>
  <option value="-record_date">Transaction Date</option>
  <option value="address">Address</option>
  <option value="amount">Amount</option>
</select>
{% endblock extra_form %}
<!-- Partial template goes here -->
{% block extra_script %}
<script>
  $(function(){
    // prepopulate sort_by field
    var category_str = "{{request.GET.category}}";
    if (category_str && category_str.length > 0) {
      $('#category').val(category_str);
    }
  });
</script>
{% endblock extra_script %}

templates/transactions/get_tax_report.html
{% extends '_base.html' %}

{% block content %}
    <form action="" method="POST" enctype="multipart/form-data">{% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-info ml-2" type="submit">Go</button>
    </form>
{% endblock content %}

templates/transactions/matching_expense_list.html
{% extends '_base.html' %}
{% load humanize %}

{% block content %}

<table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">Transaction Date</th>
        <th scope="col">Account Number</th>
        <th scope="col">Statement Type</th>
        <th scope="col">Transaction Description</th>
        <th scope="col">Transaction Amount</th>
        <th scope="col">Accounting Classification</th>
        <th scope="col">Verified ?</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>{{ target_transaction.transaction_date }}</td>
        <td>{{ target_transaction.statement.account_number }}</td>
        <td>{{ target_transaction.statement.statement_type }}</td>
        <td style="word-wrap: break-word;min-width: 160px;max-width: 160px;">{{ target_transaction.transaction_description }}</td>
        <td>{{ target_transaction.transaction_amount|intcomma }}</td>
        <td>{{ target_transaction.accounting_classification }}</td>
        <td>{{ target_transaction.is_verified }}</td>
        <td><a href="{% url 'transaction_edit' target_transaction.pk %}">Edit</a></td>
     </tr>
    
    </tbody>
  </table>

<h1>
{% if object_list|length > 1 %}
{{ object_list|length }} potential matches found:
{% else %}
{{ object_list|length }} potential match found:
{% endif %}
</h1>
<button class="btn text-white btn-primary w-25" hx-target="next tbody" hx-swap="afterbegin" hx-get="{% url 'add_matching_expense' %}">Add an expense</button>
<table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">Expense Date</th>
        <th scope="col">Address</th>
        <th scope="col">Expense Type</th>
        <th scope="col">Expense Amount</th>
        <th scope="col">Invoice Image</th>
        <th scope="col">Note </th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      {% if object_list|length > 0 %}
        {% for expense in object_list %}
          {% include 'transactions/partial/matching_expense_row.html' with expense=expense target_transaction=target_transaction  %}
        {% endfor %}
      {% endif %}
    </tbody>
</table>

{% endblock content %}

templates/transactions/matching_revenue_list.html
{% extends '_base.html' %}
{% load humanize %}

{% block content %}

<table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">Transaction Date</th>
        <th scope="col">Account Number</th>
        <th scope="col">Statement Type</th>
        <th scope="col">Transaction Description</th>
        <th scope="col">Transaction Amount</th>
        <th scope="col">Accounting Classification</th>
        <th scope="col">Verified ?</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>{{ target_transaction.transaction_date }}</td>
        <td>{{ target_transaction.account_number }}</td>
        <td>{{ target_transaction.statement_type }}</td>
        <td>{{ target_transaction.transaction_description }}</td>
        <td>{{ target_transaction.transaction_amount|intcomma }}</td>
        <td>{{ target_transaction.accounting_classification }}</td>
        <td>{{ target_transaction.is_verified }}</td>
        <td><a href="{% url 'transaction_edit' target_transaction.pk %}">Edit</a></td>
     </tr>
    
    </tbody>
  </table>

<h1>
{% if object_list|length > 1 %}
{{ object_list|length }} potential matches found:
{% else %}
{{ object_list|length }} potential match found:
{% endif %}
</h1>
<a class="btn btn-primary" role="button" href="{% url 'create_matching_revenue' target_transaction.pk %}">Add a revenue</a>
<table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">Revenue Date</th>
        <th scope="col">Address</th>
        <th scope="col">Revenue Type</th>
        <th scope="col">Amount</th>
        <th scope="col">Check Image</th>
        <th scope="col">Note </th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <!--{% if object_list|length > 0 %} -->
        {% for revenue in object_list %}
        <tr>
          <td>{{ revenue.record_date }}</td>
          <td>{{ revenue.address }}</td>
          <td>{{ revenue.get_revenue_type_display }}</td>
          <td>${{ revenue.amount|intcomma }}</td>
          <td><a href="{{ revenue.display_full_path_to_gcs }}">{{ revenue.document_image.name }}</a></td>
          <td>{{ revenue.note }}</td>
          <td><a href="{% url 'revenue_edit' revenue.pk %}">Edit</a></td>
          <td><a href="{% url 'match_revenue' target_transaction.pk revenue.pk %}">Select</a></td>
        </tr>
        {% endfor %}
       <!--{% else %} -->
       
       <!--{% endif %} -->
    </tbody>
</table>

{% endblock content %}

templates/transactions/revenue_edit.html
{% extends '_base.html' %}

{% block content %}
    <a href="{% url 'revenue_list' %}">Back to revenues</a>
    <h1>Edit</h1>
    <form action="" method="POST" enctype="multipart/form-data">{% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-info ml-2" type="submit">Update</button>
        <!-- input type="hidden" name="next" value="{{ request.META.HTTP_REFERER }}"> -->
    </form>
{% endblock content %}

templates/transactions/revenue_list.html
{% extends '_record_list_ajax.html' %}
{% load humanize %}


{% block extra_form %}
&nbsp;&nbsp;
<label for="order_by"> Sort by: </label>
<select name="order_by" id="order_by" value="">
  <option value="-date_filed">New</option>
  <option value="-record_date">Transaction Date</option>
  <option value="address">Address</option>
</select>
{% endblock extra_form %}

templates/transactions/statement_delete.html
{% extends '_base.html' %}

{% block content %}
    <h1>Delete Statement</h1>
    <form action="" method='POST'>{% csrf_token%}
        <p>Are you sure you want to delete the statement on "{{statement.statement_date}}"</p>
        <input type="submit" value="Confirm">
    </form>
{% endblock content %}

templates/transactions/statement_list.html
{% extends '_base.html' %}
{% load humanize %}

{% block content %}

<a class='btn text-white bg-primary' href="{% url 'upload_statement' %}">Upload a new statement</a>
<br>
<table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">Ending Date</th>
        <th scope="col">Type</th>
        <th scope="col">Account Number </th>
        <th scope="col">Uploaded file</th>
        <th scope="col">Is verified? </th>
        
        <th></th>
      </tr>
    </thead>
    <tbody>
      {% for statement in object_list %}
      <tr>
        <td><a href="{% url  'transaction_list' %}?statement_id={{ statement.id }}">{{ statement.period_ending_date }}</a></td>
        <td>{{ statement.get_statement_type_display }}</td>
        <td>{{ statement.account_number }}</td>
        <td><a href="{{ statement.get_full_path_to_gcs }}"> {{ statement.uploaded_file.name }}</a></td>
        <td>{{ statement.is_verified }}</td>
        <td><a href="{% url 'statement_delete' statement.pk %}">Delete</a>  </td>
       
      </tr>
      {% endfor %}
    </tbody>
  </table>

{% endblock content %}

templates/transactions/statement_upload.html
{% extends '_base.html' %}
{% block content %}
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
       {{ form.as_p }}
       <button type="submit">Upload</button>
    </form>

{% endblock content %}